---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install python
  apt: name=python3 state=present

- name: Install python3-pip
  apt: name=python3-pip state=present          


- name: Install python dev modules
  apt: name={{ item }} state=present
  with_items:
  - libxml2-dev
  - libxslt1-dev
  - libldap2-dev
  - libsasl2-dev
  - libtiff5-dev
  - libjpeg8-dev
  - libopenjp2-7-dev
  - zlib1g-dev
  - libfreetype6-dev
  - liblcms2-dev
  - libwebp-dev
  - libharfbuzz-dev
  - libfribidi-dev
  - libxcb1-dev
  - libpq-dev

